plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.8-SNAPSHOT'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
	maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.0.1'
	runtimeOnly 'com.oracle.database.jdbc:ojdbc11'
	// JSP 화면(Jasper)을 해석하기 위한 엔진 (필수!)
	implementation 'org.apache.tomcat.embed:tomcat-embed-jasper'
	// JSP에서 jstl(태그 라이브러리)을 편하게 쓰기 위한 도구 (권장!)
	implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:4.0.1'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
